### ISSUE TITLE
Link to this port is broken on the website

### ISSUE THREAD

**Issue by jdahm** [arcticicestudio/nord-terminal-app#11]
Link goes to https://www.nordtheme.com/ports/terminal-app.

**Comment by arcticicestudio** [comment]
Hi @jdahm :wave:, thanks for your contribution :+1:

I'm not exactly sure what you mean exactly, but the link with the text “repository on GitHub“ correctly targets this repository. But if you mean that the port page itself does not look like others ports, e.g. the one from for [Visual Studio Code“][2], the reason is simple: there has been no time to implement it yet :smile:
The progress of the data migration is tracked in https://github.com/arcticicestudio/nord-docs/issues/133 and ports for terminal applications are pending due to lack of free time and the fact that they will use shared code to prevent duplicate code.

[1]: https://www.nordtheme.com/ports/terminal-app
[2]: https://www.nordtheme.com/ports/visual-studio-code

**Comment by jdahm** [comment]
Thanks for the quick response! 💯 

Apologies, I wrote this in a hurry so that I would remember, but wasn't clear. When a user goes to https://www.nordtheme.com/ports and clicks on [Nord Terminal.app](https://www.nordtheme.com/ports/terminal-app), it takes them to a dead page. Just wanted to alert you to that in case it was not intended.

Your comment clarifies it completely. It seems like there just hasn't been time to make a nice landing page like that for [tmux](https://www.nordtheme.com/ports/tmux), and others are dead links as well.

Thanks for a great theme! I'll continue to use it where I can.
