### ISSUE TITLE
Character covered by block cursor is invisible

### ISSUE THREAD

**Issue by laxman20** [arcticicestudio/nord-terminal-app#5]
The character under the cursor should be seen as is the case with iTerm2.

![screen shot 2018-03-23 at 5 36 30 pm](https://user-images.githubusercontent.com/1408115/37854895-353e98f4-2ec3-11e8-937c-82d3a1ad6f54.png)

**Comment by trevordmiller** [comment]
I noticed this as well. I don't believe Mac terminal.app supports a different text color for the cursor, so perhaps the default cursor color could be changed to another one of the Nord values that works well over dark / light text?

**Comment by arcticicestudio** [comment]
@trevordmiller That is indeed a limitation of the app itself. It works fine for smarter terminals like [iTerm2][it] because it automatically inverts the foreground color using the color of the block cursor. In my opinion Apple should simply hire the iTerm2 author(s)/maintainer(s) and make it the default, the _Terminal.app_ is like light-years behind the development and stability of the polished iTerm2 app and looks more like a started and not finished trainee project.

I'll close this ticket for now since it has unfortunately gone down in the amount of daily notifications and was also resolved on the user-side in https://github.com/arcticicestudio/nord-vim/issues/113 by reducing the opacity of the cursor color.

[it]: https://github.com/arcticicestudio/nord-iterm2

**Comment by trevordmiller** [comment]
Sounds good. I personally prefer terminal.app to iTerm2 because it is significantly more lightweight / more performant in some situations.
