### ISSUE TITLE
Suggestion to default cursor to block, non-blinking

### ISSUE THREAD

**Issue by trevordmiller** [arcticicestudio/nord-terminal-app#7]
Suggestion to default cursor to block, non-blinking - like the default. Not a big deal, but I was thrown off by the non-standard line + blinking.

**Comment by arcticicestudio** [comment]
Hi @trevordmiller :wave:, thanks for your contribution :+1:
The _line_ cursor is used by default on purpose to prevent problems like #5 that can't be fixed by theme authors since it is a limitation of the app itself.
The cursor style can simply be changed through the _profile preferences_ by users who prefer the cursor block style.

We can add a section in the upcoming FAQ on the official port project website documentation (see https://github.com/arcticicestudio/nord-docs/issues/133 for a status process) to better clarify this design decision and guide users through the change process.
I'll leave this issue open to track this TODO.
